Shschedrov Bohdan Laboratorna 2/Models/Company.cs
namespace Shschedrov_Bohdan_Laboratorna_2.Models
{
    public class Company
    {
        public string Name { get; set; }
        public int Employees { get; set; }
    }

}

Shschedrov Bohdan Laboratorna 2/Models/ErrorViewModel.cs
namespace Shschedrov_Bohdan_Laboratorna_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Shschedrov Bohdan Laboratorna 2/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using Shschedrov_Bohdan_Laboratorna_2.Services;
using Shschedrov_Bohdan_Laboratorna_2.Models;

namespace Shschedrov_Bohdan_Laboratorna_2.Controllers
{
    public class CompanyController : Controller
    {
        private readonly CompanyService _companyService;

        public CompanyController(CompanyService companyService)
        {
            _companyService = companyService;
        }

        public IActionResult Index()
        {
            var largestCompany = _companyService.GetLargestCompany();
            return View(largestCompany);
        }
    }
}

Shschedrov Bohdan Laboratorna 2/Controllers/DataController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Collections.Generic;
using System.IO;

namespace Shschedrov_Bohdan_Laboratorna_2.Controllers
{
    public class DataController : Controller
    {
        public IActionResult Index()
        {
            var jsonData = System.IO.File.ReadAllText("Config/mydata.json");

            var personalData = JsonSerializer.Deserialize<Dictionary<string, string>>(jsonData);

            return View(personalData);
        }
    }
}

Shschedrov Bohdan Laboratorna 2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shschedrov_Bohdan_Laboratorna_2.Models;
using System.Diagnostics;

namespace Shschedrov_Bohdan_Laboratorna_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Shschedrov Bohdan Laboratorna 2/Views/Company/Index.cshtml
@model Shschedrov_Bohdan_Laboratorna_2.Models.Company

<h1>The company with the most employees:</h1>
<p>@Model.Name - @Model.Employees employees</p>

Shschedrov Bohdan Laboratorna 2/Views/Data/Index.cshtml
<h1>About me</h1>
<ul>
    @foreach (var entry in Model)
    {
        <li>@entry.Key: @entry.Value</li>
    }
</ul>

Shschedrov Bohdan Laboratorna 2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Shschedrov Bohdan Laboratorna 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shschedrov_Bohdan_Laboratorna_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shschedrov_Bohdan_Laboratorna_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shschedrov_Bohdan_Laboratorna_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="">Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="">About me</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Shschedrov_Bohdan_Laboratorna_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>